### ISSUE TITLE
language identifiers and language varieties: distinguish language identifiers in addition to glottocode in badges

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#13]
This becomes evident when looking at badges created with the `readme` function in lexibank: For Chinese dialects, where we have mutually unintelligible varieties with the same glottocode, a dataset of 40 varieties shrinks down to twelve. We need to find a way to handle the identifiers, counting not only the available glottocodes, but the names, or specific ids, then submitted. Otherwise, both counts on cognates, words, coverage, etc., will be wrong, as they suggest a high degree of synonymy (imagine 4 languages with same glottocode, with each 200 words for 200 concepts would look like 800 words for 200 concepts), etc.

Either, we find a way for quick assignment of glottocodes, or we need to allow for explicit identifiers based on name + glottocode or the like.

**Comment by xrotwang** [comment]
Don't know how quick you need this, but I'm looking examples to document how glottolog can be expanded right now, and this seems to be a good case for this! So if "in the next couple of weeks" is quick enough, we should add these varieties to glottolog.

**Comment by LinguList** [comment]
it is definitely quick enough, and for me, it would be even more interesting in adding these to glottolog than making some workarounds which are difficult to handle.

I have all geo-coordinates for the varieties as well.

**Comment by xrotwang** [comment]
Cool! Please open a ticket on `clld/glottolog` and provide the coordinates, names and which language they are dialects of!

**Comment by LinguList** [comment]
ticket means: issue?

**Comment by xrotwang** [comment]
yes, please.

**Comment by xrotwang** [comment]
Actually, you may be right that the summary statistics are unintuitive when only counting different glottocodes. This became apparent when computing the synonymy index for `gbd`. Only distinguishing glottocodes it came out as 1.25, distinguishing local language names it is the expected 1.0.

So maybe we should put the code I used to determine local language IDs into a function and use this for stats:
```python
def lid(row):
    return row.get( 'Language_local_ID', row.get('Language_name', row.get('Language_ID')))
```

**Comment by LinguList** [comment]
yep, I completely agree with this. There is the danger (but this is already the case) that we will have identical languages with different LIDs in our data, but given that we have the problem of incomplete mapping, or rough glottocode mapping apparently across many datasets, we need to be aware of this.

And in cognate detection and other tasks, I would never sample after glottocode only, but always follow local identifiers, as people often have these datasets with very mixed representation.

**Comment by d97hah** [comment]
Yes please, and do let me know which mutually intelligible Chinese dialects
have the same glottocode.

2016-07-27 17:28 GMT+02:00 Robert Forkel <notifications@github.com>:
