### ISSUE TITLE
Galucio 2015 data on Tupi

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#18]
Data from the paper by Galicio et al (2015) on Tupi (nice cognate judgments).

**Comment by SimonGreenhill** [comment]
http://www.scielo.br/scielo.php?pid=S1981-81222015000200229&script=sci_arttext

PDF: http://www.scielo.br/pdf/bgoeldi/v10n2/2178-2547-bgoeldi-10-02-00229.pdf

**Comment by xrotwang** [comment]
I thought we could parse them from [the HTML](http://www.scielo.br/scielo.php?pid=S1981-81222015000200229&script=sci_arttext#app1). Turns out, though, that the actual wordlists are ... [an image](http://www.scielo.br/img/revistas/bgoeldi/v10n2//2178-2547-bgoeldi-10-02-00229-gf12.jpg).

**Comment by SimonGreenhill** [comment]
...yep :) Although looking at the PDF, it seems to be cut and pastable:

```
001-I
Mu ṍn, Ku õn, Wa õn, Ma õn, Tu õn, Ak õn, Me õn, Xi una, Ju una, Ka ʔõn, Pu ʔõn, Ar õõt, Gv õõt, Zo õõt, Sa õõt,
Su ó.ẽn, Kt ĩn || Pg ʃe, Uk ihẽ, Ta ie, Pt ji(hi), Aw ito, Mw ujto ||

002-YOU
Aw ʔen, Mw en, Mu ẽń , Ku ẽn, Wa ʔẽn, Ma ẽn, Tu ẽn, Ak en, Me ẽt, Xi ena, Ju ena, Ka ʔẽn, Pu ʔẽn, Ar ẽẽt, Gv ẽẽt,
Zo ẽẽt, Sa ẽẽt, Su é.ẽn, Kt ãn || Pg nde, Uk nde, Ta ane, Pt nde(he) ||
```

**Comment by xrotwang** [comment]
you are right. `pdftotext` does the trick, too.

**Comment by LinguList** [comment]
well, actually, I had the data already almost parsed by just copying it from pdf. A few errors were left, but I gladly share what I have so far.

**Comment by LinguList** [comment]
[Archiv.zip](https://github.com/glottobank/lexibank-data/files/392332/Archiv.zip)

okay, you can compare this: the attached archive contains the files I used for parsing: 

* one file called "raw" where I copied the pdf manually and put it into a text-file, where I then excluded the comments again manually
* parse.py: a simple script that parses the data in lingpy-style, using a whitelist to account for cases which need to be manually adjusted

I don't remember, but I think I only managed to do the first part of the data (the basic vocabulary list), not more, but I need to check later.

But basically, the script in the archive should do the trick.

**Comment by xrotwang** [comment]
ok. will work from there.

**Comment by LinguList** [comment]
I added more stuff than needed, as you'll see, since I wanted to have it segmented, etc. for lingpy testing of cognate detection, so having it in a not completely ipa-like form should be even more straightforward...

**Comment by xrotwang** [comment]
@LinguList I tried to correct language IDs in the swadesh lists as [shown here](https://github.com/glottobank/lexibank-data/commit/7470f9ec81dc1f64782b82f69cd079ba82120aa3). Given the overall consistency of the lists, I think this - i.e. assuming wrong language IDs to be typos - makes sense. What do you think?

**Comment by xrotwang** [comment]
@LinguList Never mind. I figured out how to deal with the output of `pdftotext` without manual interventions.
