### ISSUE TITLE
write CLPA/transcription report to file

### ISSUE THREAD

**Issue by xrotwang** [glottobank/lexibank-data#23]
It would be good to write the transcription report to a file. Maybe already formatted in markup, or possibly even better, a JSON file which could be read when creating the README.md.

**Comment by xrotwang** [comment]
As far as I understood, the current transcription report is per CLDF dataset. I think that makes sense, and could be reflected in the JSON data. Is there a meaningful summary across CLDF datasets we could include in the README.md?

**Comment by LinguList** [comment]
first, the transcriptoin report could be expanded to a language-specific level, useful for error tracking (but probably more useful in general clpa, when still working with a dataset).

As a summary for the transcription report, I suggest the error-rate, either including full number of tokens or two discrete scores types and tokens, so this would be:

* number of tokens - number of erroneous tokens / number of tokens (percentage of accuracy)
* same for types (may differ, as errors usually occur in spurious types)

This will yiedl in two badges:

* lingpy-transcription-accuracy (does lingpy tolerate/recognize the chars?)
* clpa-transcription-compatibility (does clpa tolerate it?)

Furthermore, the number of distinct sound is also interesting (for each dataset). The number of sounds per language on average would also be cool (as it is an indicator of phonetic diversity, if we have low error-rates in clpa and lingpy).

The former are straightforward to be derived for the currently calculated thing. The latter (per language number of sounds) would require some editing of the function (but potentially also only a few lines).

So, summary:

measure | aspect | score 
--- | --- | ---
transcription-quality | tokens in lingpy | 0-1 / %
transcription-quality | tokens in clpa | 0-1 / %
transcription-quality | types in lingpy | 0-1 / %
transcription-quality | types in clpa | 0-1 / %
number of sounds | per dataset | int
number of sounds | per language | float

**Comment by LinguList** [comment]
I guess we can close this for the moment, as it is basically solved now, and details about the rport can be put inot new issues.
