### ISSUE TITLE
extend Cognates and Alignments objects to include method info

### ISSUE THREAD

**Issue by xrotwang** [glottobank/lexibank-data#36]
It should be possible to store the method used to derive at an alignment or cognate judgement, and "expert" (or similar) should be a reserved method identifier, signifying the judgement was arrived at by a linguist.

**Comment by LinguList** [comment]
ideally, even by giving the expert a name, I'd say, given that we have quite some information on that for some databases.

**Comment by xrotwang** [comment]
Hm. I think we may have two cases:
1. The expert is the creator of the dataset. In that case the name of the expert should be available in the accompanying metadata file.
2. The expert cites a source. In that case we should reuse (i.e. add to the cognates or alignments file) the `Source` column, which is already specified for the CLDF data file.

**Comment by LinguList** [comment]
yes, that sounds like a good plan.
