### ISSUE TITLE
should we add nexus files if available?

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#43]
This might be an interesting service for people who like to make trees and the like: if we have cognate sets, it is straightforward to make some nexus-output (we can use LingPy for this), and we could offer output in this format for each datset that has cognates.

**Comment by xrotwang** [comment]
Dunno whether we should provide the NEXUS, or rather provide a subcommand to create such a file. From what I hear, NEXUS is so ill-specified that we may easily run into "I want NEXUS that works with software xyz"-type questions.

**Comment by SimonGreenhill** [comment]
Closed in favor of https://github.com/glottobank/pycldf/issues/11
