### ISSUE TITLE
Ainu Basic Vocabulary Lists (ABVL) 

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#48]
Sean Lee actually also gave us the ainu data. But I couldn't find it in the lexibank database list. So we should include it at some point.

**Comment by QuentinAtkinson** [comment]
I asked Sean to send this to us back in December. He cc’d Mattis and Robert, so you guys should have it. Let me know if you want me to resend it. Sean gave his express permission to include it in Lexibank.

Q

On 27 Aug 2016, at 20:38, Johann-Mattis List <notifications@github.com<mailto:notifications@github.com>> wrote:


Sean Lee actually also gave us the ainu data. But I couldn't find it in the lexibank database list. So we should include it at some point.

**Comment by LinguList** [comment]
I have it! Just need to set it up for parsing, which may take a while,  depending on the arrangements. Will push raw data tomorrow. We should not forget to keep a list with people to thank and also contact them upon launch, or some week before, so thes may further inspect their data. ..


Sent from the road


-------- Ursprüngliche Nachricht --------
Von: Quentin <notifications@github.com> 
Datum:27.08.2016  23:45  (GMT+01:00) 
An: glottobank/lexibank-data <lexibank-data@noreply.github.com> 
Cc: Johann-Mattis List <mattis.list@lingpy.org>, Author <author@noreply.github.com> 
Betreff: Re: [glottobank/lexibank-data] ainu database (#48) 

I asked Sean to send this to us back in December. He cc’d Mattis and Robert, so you guys should have it. Let me know if you want me to resend it. Sean gave his express permission to include it in Lexibank. 

Q 

On 27 Aug 2016, at 20:38, Johann-Mattis List <notifications@github.com<mailto:notifications@github.com>> wrote: 


Sean Lee actually also gave us the ainu data. But I couldn't find it in the lexibank database list. So we should include it at some point.

**Comment by LinguList** [comment]
closing this, since we have the data in there now.
