### ISSUE TITLE
Keep Track of Acknowledgements

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#53]
There are some very nice people who gave us their unpublished data, and we should not forget to thank them. Let's keep this issue to track down all relevant names.

* Sean Lee (Japonic + Ainu)
* Andrew Kitchen (Semitic)
* Wang Feng (Chinese)

**Comment by xrotwang** [comment]
Should we do this in a `CONTRIBUTORS.md` file?

**Comment by LinguList** [comment]
yes, good idea!

**Comment by LinguList** [comment]
I just further refined it a bit, also to show which kind of contribution we should try to track.

Huber and Reed is thanks to a grant project by M. Cysouw, and many people were involved in its digitization (even more than the three I just mentioned). So the question is, how we can acknowlege this. Maybe by adding the grant number in a fourth column? By offering this service of acknowledgement also to grant organizations would be generally a good idea, I'd say...

**Comment by QuentinAtkinson** [comment]
I agree this is a good idea. This kind of facility is going to be crucial for getting people to continue to contribute. Being able to flag grant support is going to be important for many people

**Comment by LinguList** [comment]
I just added this additional information on grants. So we have four columns at the moment. We might want to put this into csv/tsv, maybe to have a more regular representation, but let's for the moment first track and see also, in how many situations this might occur, before starting to make a completely regular scheme. But we can see that we have different kinds of contributions: 

* people sending us spreadsheets of their research datasets which were published (very nice, since it saves us time, although we still have work to do, to adapt it, but it is better than to try typing things off from PDF)
* people making a real PR (future music, but I'll try to do this with @thiagochacon, also to play the potential case of this)
* people offering us access to their digitized resources (things they typed off, had digitized in projects, etc.)

And maybe, there are more cases, but these three are the most important ones I can think of right now.

**Comment by SimonGreenhill** [comment]
Ok, closing this as we've not got CONTRIBUTING.md. This can evolve as we add new datasets.

**Comment by LinguList** [comment]
we have, in fact, see [CONTRIBUTORS.md](https://github.com/glottobank/lexibank-data/blob/master/CONTRIBUTORS.md). But let's just make sure to not forget to list all people. It's easier doing it whenever on adds a dataset than afterwards. We might as well mention some people in our report on Saturday. Thiago should definitely be mentioned in the report, as he was closely involved also in our discussions during the last weeks, but I guess, he'll also speak up in the discussion afterwards, as the question of DOIs, encouraging people contributing their data, and different degrees of dephts of analysis is "simulated" with Thiago's data on Tukano.
