### ISSUE TITLE
Cross-Referencing among dataset problems, taking Bai Dialect Survey as example

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#55]
I just realized a problem we need to be careful with when dealing with new datasets where no original data is provided but simply judgments (cognates, aligments): often, such an analysis will further change certain entries, be it that the original data was mis-interpreted in a first run, or that one deliberately changes the interpretation. This happened with BDS (in PR #54), when I first added the strict source, and then realized they had these ugly multi-entries separated by dashes in the data. So I split them, to make true cognates, and currently, as a first idea, retained the original IDs, to allow for back-tracking. But what I essentially did not was a fork of the BDS which I then turned into CBDS (adding cognates). So adding only the cognates is not the right representation for the data by now, as I changed not all, but quite a few of the entries which I refer to. I only changed the field SEGMENTS (or TOKENS), not the original entry, but I doubled entries to allow for separate tokenized representations. It seems, it is easier to add a new dataset also with the CLDF for the normal Wordlist plus Cognates, but keep some way to reference the earlier one. Or is there any other way we can handle this?

We will face he same when @thiagochacon provides the Huber-cognates, as there we also have non-split entries with multiple forms and variants.

**Comment by LinguList** [comment]
I just re-though the whole claim, and now I think that the following should work:

* referencing a dataset is done by using the key of the word (the entry in the wordlist)
* if the entry is "splittable", containing, e.g., more than one word, or potentially also partial cognates, the entry itself may be assigned to multiple cognate sets (as is current practice in ABVD and IELex)
* content which is newly created relates to the alignment, and the segmentation, as these are the access points where the data is parsed, etc. We allow that these are edited or overwritten, and since an alignment is equivalent to the column "SEGMENTS" minus the markup ("-", "(", ")", etc.), we are still consistent, and people could even create a new wordlist with more entries from this modification to a list without cognate sets etc.

**Comment by xrotwang** [comment]
I think you are right, that in case of changes (which is the more common case, I guess) there should be a CLDF wordlist in the derived dataset, too. References to the original data could be encoded using [weak linking](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#weak-linking-between-tables) (e.g. using fragment identifiers like `#<dataset-ID>-<word-ID>`). The only problem I see with too many near-copies of datasets would be clutter and duplication in the lexibank app. But I think this could be resolved with appropriate metadata - e.g. a flag signaling a cognate-judgement only dataset, in which case the changed form is only stored as attribute of the cognacy judgement and not as separate counterpart instance.

**Comment by LinguList** [comment]
I'm just about to finalize the example for BDS and CBDS, where you can see the extend of changes that are at least normal and to be expected when working on a dataset. I suppose I push this to the current PR, so we have something to discuss and to think of solutions. In fact, I derive a dataset there, but I currently only reference the original, since changes only apply to the Value field and are given in the alignemnts themselves.

**Comment by xrotwang** [comment]
And yes, partial cognates could be handled using attributes of the cognacy judgement as well. E.g. by storing only the "matching" part of the form with the cognacy judgement.

**Comment by LinguList** [comment]
> And yes, partial cognates could be handled using attributes of the cognacy judgement as well. E.g. by storing only the "matching" part of the form with the cognacy judgement.

ideally, we have a clear segmentation in the data, e.g., using a symbol in the segmentation, as a "+", indicating parts of the word, and then we could reference several strings as partially cognate, but adding as a part of the meta-information, WHERE they are cognate, using a simple index. Yet for a start, we could probably also do without this and just modify the alignment column, which would then only show the aligned part in the word.

**Comment by xrotwang** [comment]
Ok, so here is how I think we should handle derived datasets:

1. The fact that a dataset is derived from another dataset should be stated using 
    - [dc:isVersionOf](http://dublincore.org/documents/dcmi-terms/#terms-isVersionOf) to link to source dataset
    - [dc:provenance](http://dublincore.org/documents/dcmi-terms/#terms-provenance) to describe how it was derived
2. The derived dataset comprises it's derived version of the original data, i.e. it should
    - either implement (or import) identical `download` functions, if all changes can be applied automatically
    - or download the raw data from a published version of the derived data
    - or provide the derived raw data in `glottobank/lexibank-data`.
3. The derived dataset must implement a `cldf` function - which may be similar to the one for the source dataset, but should only be imported if the maintainers of both datasets are identical.

**Comment by xrotwang** [comment]
@LinguList So if we restrict cross-references between datasets to some `dc` elements in the metadata, I think we can close this issue, right?

**Comment by LinguList** [comment]
yep, so we basically allow for cross-referencing, but we make new data anyway. yes, this little etude on Bai cognates more or less clearly showed that. And now I'm in the lucky "possession" of a huge bunch of partial cognates on these languages!
