### ISSUE TITLE
leeainu: relating cognate set IDs to forms

### ISSUE THREAD

**Issue by xrotwang** [glottobank/lexibank-data#60]
In the `leeainu` dataset, multiple forms and multiple cognate set IDs may be assigned to one language and one concept. This is encoded by concatenating all forms using a `;` as separator, e.g. `'anokay;co'okay` and concatenating cognate set IDs using `&` as separator, e.g. `2&3`. I think ideally, we would like to split the forms into separate CLDF values. Unfortunately, the order of cognate set IDs does not necessarily correspond to the order of forms as can be seen in this snippet:
```
多蘭泊,Tarantomari,'anoka(y),3
真岡,Maoka,'anokay;co'okay,2&3
白浦,Shiraura,ku'ani;co'okay,1&2
```
@LinguList could alignments help here?

**Comment by LinguList** [comment]
yes, definitely, but it might even be quicker to parse the data into the EDICTOR and quickly adjust these cases, using the partial cognate annotation tool. First, partial cognates are below 50 concepts, even less, so will take some 20 minutes to resolve. All that needs to be done is turn the data into a spradsheet, tab-separated, lingpy-format, in which words are splitted by adding a "+", and cognates are splitted by space. I can then quickly use the EDICTOR to annotate these.
But the more I think about it, even a manual solution in the script may be enough. All it requires is to re-order the column by concept and doculect. If you provide an initial mapping in the parser, we can add this later step by step (I volunteer to go for it if I find time).

Alignments would require to make some cluster analysis of all words, check where they are, which cogid they have when being separated, and getting a score. This seems like an overkill for the small amount of examples. But given the difference between the words, it would surely help (as would edit distance)...

**Comment by xrotwang** [comment]
Hm. Ok. So this would be some pre-processing, to create the raw data. This wouldn't be enough input to warrant a second derived dataset, though?

**Comment by LinguList** [comment]
Nope, I don't think so. I'd even say that the pre-processing could be done just from the __init__ script, as it is just the re-ordering of 2&3 to 3&2 in some cases. So similar to the way we treat concepticon-mismatches...

**Comment by xrotwang** [comment]
Oh, you mean provide a hard-coded list of re-orderings? That's fine with me. Who's going to provide it, though? :)

**Comment by LinguList** [comment]
I can do that. We just need a workflow for parsing where the concepts where we have the problems are listed, so I can look it up. I doubt that there are too many actual re-orderings.

**Comment by xrotwang** [comment]
Ok, I'll seed a python dictionary which you can then re-order.

**Comment by LinguList** [comment]
or gimme five minutes, and I'll send you an explicit list of re-orderings in order of appearance.

**Comment by xrotwang** [comment]
Or lemme go first :)
I guess, even I could fix the dict here: https://github.com/glottobank/lexibank-data/blob/ad61c8f4c22a584964bbc002774687d6c4cbd588/datasets/leeainu/cogsets.py
In the comments above each mapping ow word to cogid I list all other words unambiguously assigned to a certain cognate set id.

**Comment by LinguList** [comment]
you win, I was almost through. But now I know the data better. 

"to suck" is wrongly coded:

```text
ní;númnum	1&2
sikoní;ní	2
ní;núnnun	1&2
ní;núnnun	1&2
ní	2
hópse kár	#
ni;nunnuɴ	1&2
nún;nínnun	1&2
num;ni	1&2
ni;nunnum	1&2
núnnun	1
nun	1
ni;nunnun	1&2
seru	3
nunnun;sikonun	1
nunnum:nii	1&2
sikonun	1
sikonun;nunnun;nii	1&2
nunnun;kuu	1
```
is obviously wrognly encoded, as we have often a ";" although only one number. There are more of these cases...

**Comment by LinguList** [comment]
NM19, nunnum:nii should be: nunnum;nii (mind the colon)

**Comment by xrotwang** [comment]
Yeah, I split at `:` twice and at `,` once to make the list of words as long as the list of cognate IDs.

**Comment by LinguList** [comment]
and how do you handle those cases where you have more words than IDs, like in "to suck"?

**Comment by xrotwang** [comment]
The [remaining words are mapped to `None`](https://github.com/glottobank/lexibank-data/blob/ad61c8f4c22a584964bbc002774687d6c4cbd588/datasets/leeainu/cogsets.py#L321-L328), just like `itertools.izip_longest` does

**Comment by LinguList** [comment]
[re-order.txt](https://github.com/glottobank/lexibank-data/files/449878/re-order.txt)

anyway, just to compare, I add my re-orders, given that I already made them. But it shoudl be fine with your solution. 

We really NEED these formats that people just agree upon to avoid these kinds of problems that cost us lots of time to add the data...

**Comment by xrotwang** [comment]
So I guess in the case linked above, the corrected mapping would be:
```python
{
        "nís": 1,
        "nískur": 1,
        "'úrar": 3,
},
```

**Comment by LinguList** [comment]
agree

**Comment by xrotwang** [comment]
I think my version of the re-ordering is a bit more readable.

**Comment by LinguList** [comment]
:-) but mine was manually crafted, using speed-typing and VI! Yet I definitely agree.

**Comment by xrotwang** [comment]
So should I go ahead and fill it in or are you?

**Comment by LinguList** [comment]
please go ahead!
