### ISSUE TITLE
Deepadung et al. (2015), data on Palaung languages

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#65]
Very interesting data set, with cognate coding and excellent IPA, as far as I can see. Some 20 (10-20 ?) languages, interesting geographically, and interesting to be compared against the Sidwell data.

Published with Creative Commons Attribution License, but PDF is hard to digitize, although data is in tabular form.

Article here:

* www.sealang.net/mks/mks44sujaritlak.pdf

**Comment by LinguList** [comment]
Update: I just added the list by Deepadung to the concepticon (https://github.com/LinguList/concepticon-data/blob/master/concepticondata/conceptlists/Deepadung-2015-100.tsv), and I contacted them for the spreadsheet.

**Comment by LinguList** [comment]
Update: just got the data, it is already pushed, and Deepadung is listed in list of contributors.

**Comment by SimonGreenhill** [comment]
can close?

**Comment by LinguList** [comment]
sure, I guess ;-)
