### ISSUE TITLE
AGENDA for GlottoBank Meeting 2016

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#67]
I'd suppose to take this issue as the place where we discuss in advance what we think needs discussion during the glottobank meeting. I'm thinking of questions like non-published contributions and contribution guidelines for digitized sources (interesting for @thiagochacon), CLDF format specifications, especially an update on current practice for Segmentation, and maybe suggestions for partial cognates and word-motivation (glossed morphemes) (I'm interested in that, who else?).

I suppose we just make a markdown table, and you just add to it, directly editing the link, and people may include themselves in teh last column to indicate their interest, or to nominate people they think will be interested.

**Comment by LinguList** [comment]
Please either paste the table (view raw by clicking on the edit link, or edit directly inside here)

topic | description | who is interested 
--- | --- | --- 
providing sources | digitization and modification of existing sources | @lingulist, @thiagochacon 
CLDF | discussing new specifications / thinks it should handle | @lingulist
getting sources | discussing strategies on how to approach people for sources (introductory PDF on lexibank, etc.) | @lingulist
adding sources | optimizing the workflow, outsourcing work to students | @lingulist

**Comment by LinguList** [comment]
nice to see that it works, with the editing of the tables by everybody.

**Comment by thiagochacon** [comment]
I would be interested to discuss all of these topics
