### ISSUE TITLE
Make macroarea coverage of datasets available in metadata

### ISSUE THREAD

**Issue by xrotwang** [glottobank/lexibank-data#72]
To make listings as requested in #42 easier to create, after running a dataset's `cldf` command we should compute (and store - presumably in CLDF metadata as [`dc:spatial`](http://dublincore.org/documents/dcmi-terms/#terms-spatial)) also macroareas covered in the dataset.

**Comment by LinguList** [comment]
do you need any help on this? if so, I could start with the datasets I know. We'll have, however, also the possible situation that only the subdatasets can be assigned to macroareas, and that even one dataset may cover different areas (Kessler's data, for example, which is in cogdetbench).

**Comment by xrotwang** [comment]
Each dataset can span multiple macroareas. These should be easy enough to compute - at least for anything with a glottocode.

**Comment by LinguList** [comment]
okay, so even no need to add them manually? cool
