### ISSUE TITLE
Add Cysouw et al. Mixe-Zoque data

### ISSUE THREAD

**Issue by SimonGreenhill** [glottobank/lexibank-data#84]
[cysouwMIXEZOQUE.pdf](https://github.com/glottobank/lexibank-data/files/484496/cysouwMIXEZOQUE.pdf)

**Comment by LinguList** [comment]
we should ask Michael or Søren for the raw data. But this also needs to be added to concepticon, completely forgot that this text contained a concept list...

**Comment by SimonGreenhill** [comment]
and cognates!

**Comment by LinguList** [comment]
yep, just send out an email to Søren. Let's hope he still has the data.

**Comment by LinguList** [comment]
Søren just send me the data, and I added him to the list of contributors, cognate sets will need to be taken from the PDF.
