### ISSUE TITLE
Consider storing md5/sha1 hash of remote files

### ISSUE THREAD

**Issue by SimonGreenhill** [glottobank/lexibank-data#88]
For the datasets that have raw files that are expected to be static (e.g. wheelerutoaztecan/raw/cla12078-sup-0006-supinfo6.Sheet1.csv), should we store a hash (md5, or better sha1) in __init__.py so we can track remote changes.

e.g. in \__init__.py:

```{python}
CHECKSUM = '2a2b3cb1bebfb55c44b305771b265d1d8d9355e7'
```

Having a hash would allow us to generate an error/warning on `lexibank download` or `lexibank cldf`. 

Most of the files *should* not change, but we've already seen one silent change (Grollemund Bantu). I'm particularly concerned about data file format changes to the raw files, which could lead to inconsistent results in loading the data, and this would allow us to guard against this.

On the other hand, this does not make sense for things like the ABVD where the data are loaded from an API that calls a database.

**Comment by LinguList** [comment]
I think I'd agree with this, as it is annoying having things that change silently and break our code. Often, one also encounters problems in broken links, as they are not always constantly available. So making some distinction between raw data that is not supposed to be changed, as the supplementary materials, and "fluid" data, as the ABVD, but potentially also Thiago's work on Tukano alignments, which are generated upon download?

**Comment by xrotwang** [comment]
Yes, good idea. Why would you think sha1 is better for this purpose than md5, though?

**Comment by SimonGreenhill** [comment]
md5 is broken cryptographically (and so is SHA1 for that matter, but not as badly). I know we'd only be using them as checksums and the risk of malicious data tampering is low, but sha1 is stronger than md5, and is implemented in python as well, so I think we should use the better one.

**Comment by xrotwang** [comment]
If we do use the better one, I think we should also specify this choice, e.g.
```python
CHECKSUM = ('sha1', '.....')
```
For better or worse, when it comes to checksums, I'd say if anything is a default, then it's md5.

**Comment by SimonGreenhill** [comment]
One thing to think about here is that it's not uncommon for ./raw/ to have multiple files (e.g. grollemundbantu which has Grollemund-et-al_Bantu-database_2015.Data.csv, Grollemund-et-al_Bantu-database_2015.Information.csv, Grollemund-et-al_Bantu-database_2015.Multistate.csv). 

So, do we have something in \__init__.py like this:

```{python}

CHECKSUM = {
    'Grollemund-et-al_Bantu-database_2015.Data.csv': ('sha1', '.....'),
    'Grollemund-et-al_Bantu-database_2015.Information.csv': ('sha1', '.....'),
    'Grollemund-et-al_Bantu-database_2015.Multistate.csv': ('sha1', '.....'),
}
```

...but this strikes me as clunky, and a lot of cutting and paste for dataset editors? Another alternative could be to use md5sum or sha1sum from commandline into a file (`md5sum raw/* > checksum.dat`):

```
7ea83cd59f597f682f4edefe12312623  raw/Grollemund-et-al_Bantu-database_2015.Data.csv
970ed639f19d46a5a44ade72d7296e45  raw/Grollemund-et-al_Bantu-database_2015.Information.csv
a89fa0e6e543edcbd97e327db93e4b8e  raw/Grollemund-et-al_Bantu-database_2015.Multistate.csv
```

**Comment by xrotwang** [comment]
That seems like a good idea, maybe we should copy the way this done in the [bagit](https://en.wikipedia.org/wiki/BagIt) format, i.e. have a file `manifest-md5.txt ` (md5!) in the `raw` folder?

**Comment by SimonGreenhill** [comment]
Great, if there's a format for it, let's use it. And yes we can use md5 :)

**Comment by xrotwang** [comment]
Hm. After reading a bit more about in the [bagit spec](https://tools.ietf.org/html/draft-kunze-bagit-13), it seems like we should go all the way, i.e. have the `raw` directory be a valid `bag`, so that it can be validated using
```
$ bagit.py --validate datasets/grollemundbantu/raw/
2016-09-26 17:09:39,508 - INFO - datasets/grollemundbantu/raw/ is valid
```
Unfortunately this would mean all the files must go one level deeper into `raw/data`. But I'd say it's still early enough in lexibank to do this. From my point of view it's still a win, because we can
- point to bagit docs to describe the layout of a `raw` directory,
- use bagit tools to manage these directories.

Possibly bagit may also be a good container format for the stuff in the cldf directory - at least when it comes to archiving it or shoving it into a repository to attach a DOI to it.

**Comment by SimonGreenhill** [comment]
Hmmm. I'm in favor of offloading all these problems to other people who've solved them but reluctant to add more work. On the other hand, this does look like a good solution and best practices, so perhaps it's worth the effort. Thoughts?

**Comment by LinguList** [comment]
It seems it's worth the effort, if this saves us work in the future, and with 20 datasets for the moment, I guess @xrotwang is right that it's still early enough,

**Comment by xrotwang** [comment]
Should have more time next week. Will work on this.
