### ISSUE TITLE
Better error message on missing concepticon tsv file.

### ISSUE THREAD

**Issue by SimonGreenhill** [glottobank/lexibank-data#90]
At the moment some of the lexibank cldf commands fail with error messages like:

``` python
FileNotFoundError: [Errno 2] No such file or directory: '/Users/simon/venvs/concepticon/concepticon-data/concepticondata/conceptlists/TeilDautrey-2008-430.tsv'
```

... which lead me to look inside the virtualenv .egg file for that conceptlist. I missed that I needed to specify where the concepticon repository was using `--concepticon-repos` flag (see [this](https://github.com/clld/concepticon-data/issues/194)). 

Depending on [the resolution of that issue](https://github.com/clld/concepticon-data/issues/194), there are some options:
1. rely on concepticon to package data files (upstream issue with its own pros and cons)
2. catch FileNotFoundError on loading concepticon datafiles and issue a more detailed error message ('...specify --concepticon-repos'). Easiest solution to implement.
3. include a copy of the concepticon wordlist in the dataset directory. I like this as it would have all the data in one directory, but then we need to worry about syncronising concepticon and lexibank. But, if you update a dataset, you probably need to update the concept list too, so changes here are unidirectional (concepticon -> lexibank) and should be rare (?).
4. `lexibank download` also downloads a copy of the tsv file into the dataset directory which `lexibank cldf` can rely on. I think this is the more elegant solution, but adds download overhead, and we have  committed files in the directory tree.

**Comment by xrotwang** [comment]
Option 2 seems to me the most reasonable answer. Plus better documentation on setting up a working lexibank environment. I think we want collaboration for concepticon as well as for lexibank, so users having a clone of both repositories seems to be in our interest, no?
