### ISSUE TITLE
how can I include sources in a dataset by just adding a bibtex?

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#92]
It would often be convenient to just add a bibtex file to add a given source. But how can I do that from within clld or the lexibank api? I did not find any obvious "read_bibtex(file)"-function.

**Comment by xrotwang** [comment]
Ah, ok. Will make this more obvious in pycldf. Not today, though.
Am 24.09.2016 18:27 schrieb "Johann-Mattis List" <notifications@github.com>:

**Comment by LinguList** [comment]
It's of no urgency, just wanted to note this, as I was wondering a
couple of times.

**Comment by xrotwang** [comment]
Addressed via https://github.com/glottobank/lexibank-data/blob/master/cookbook/creating_cldf.ipynb
